language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "4.2"
  - "6.9.2"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - node --version | grep -q 'v0.8' && npm install -g npm@2 || true

services:
  - redis-server
